spring:
  datasource:
    url: jdbc:postgresql://db:5432/indihive_db
    username: indihive_user
    password: ppassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
