server:
  port: 8080
  cors:
    allowed-origins: "http://localhost:3000" # Permite conexión con React

spring:
  datasource:
    url: jdbc:postgresql://db:5432/indihive_db
    username: postgres
    password: password
  jpa:
    hibernate.ddl-auto: update